apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
  namespace: mongodb
spec:
  serviceName: mongo
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
    spec:
      volumes:
        - name: secrets-volume
          secret:
            secretName: mongo-replica-auth
            defaultMode: 256
      containers:
      - name: mongo
        image: mongo:3.4
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 100m
            memory: 512Mi
        command:
        - mongod
        - --bind_ip
        - 0.0.0.0
        - --replSet
        - rs0
        - --auth
        - --clusterAuthMode
        - keyFile
        - --keyFile
        - /etc/secrets-volume/internal-auth-keyfile
        - --setParameter
        - authenticationMechanisms=SCRAM-SHA-1
        - --smallfiles
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - db.adminCommand('ping')
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - containerPort: 27017
          protocol: TCP
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
        - name: secrets-volume
          mountPath: /etc/secrets-volume
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
